"""empty message

Revision ID: 93717c9e3fee
Revises: 1880b6d24e1c
Create Date: 2025-08-22 19:14:58.170877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93717c9e3fee'
down_revision = '1880b6d24e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('rotation', sa.String(length=48), nullable=False),
    sa.Column('gravity', sa.String(length=48), nullable=False),
    sa.Column('diameter', sa.String(length=48), nullable=False),
    sa.Column('terrain', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
